// redux/constants/electionConstants.js
export const ELECTION_LIST_REQUEST = 'ELECTION_LIST_REQUEST';
export const ELECTION_LIST_SUCCESS = 'ELECTION_LIST_SUCCESS';
export const ELECTION_LIST_FAIL = 'ELECTION_LIST_FAIL';

export const ELECTION_DETAILS_REQUEST = 'ELECTION_DETAILS_REQUEST';
export const ELECTION_DETAILS_SUCCESS = 'ELECTION_DETAILS_SUCCESS';
export const ELECTION_DETAILS_FAIL = 'ELECTION_DETAILS_FAIL';

export const ELECTION_CREATE_REQUEST = 'ELECTION_CREATE_REQUEST';
export const ELECTION_CREATE_SUCCESS = 'ELECTION_CREATE_SUCCESS';
export const ELECTION_CREATE_FAIL = 'ELECTION_CREATE_FAIL';

export const ELECTION_UPDATE_REQUEST = 'ELECTION_UPDATE_REQUEST';
export const ELECTION_UPDATE_SUCCESS = 'ELECTION_UPDATE_SUCCESS';
export const ELECTION_UPDATE_FAIL = 'ELECTION_UPDATE_FAIL';

export const ELECTION_DELETE_REQUEST = 'ELECTION_DELETE_REQUEST';
export const ELECTION_DELETE_SUCCESS = 'ELECTION_DELETE_SUCCESS';
export const ELECTION_DELETE_FAIL = 'ELECTION_DELETE_FAIL';
